### ISSUE TITLE
Modificateurs dans le calculateur de caractéristiques

### ISSUE THREAD

**Issue by cseccia** [em-squared/heros-et-dragons-drs#24]
Salut !
Les modificateurs sont mauvais dans le calculateur, a 11 dans la carac donné, l'outil sort +1 alors qu'il devrait être à 0 ! J'ai trouvé une super doc qui explique comment les modificateurs fonctionnent https://heros-et-dragons.fr/utiliser-les-caracteristiques/#valeurs-de-caracteristiques-et-modificateurs-2 ;)

PS: ça pourrait être bien d'avoir un outil de création de perso en ligne ! (je peux surement donner un coup de main si jamais je me mets sur vue.js)

**Comment by em-squared** [comment]
Je ne reproduis pas le bug, et je suis sûr que le calcul est juste.
Tu as bien vérifié qu'il n'y a pas de modificateur racial qui fait passer la carac à 12 ou 13 avec un score de base à 11 ?

Si tu es sûr qu'il y a un bug, peux-tu fournir une méthode de reproduction fiable ?
