### ISSUE TITLE
Le site H&D n'est pas explorable depuis Google Translate

### ISSUE THREAD

**Issue by paercebal** [em-squared/heros-et-dragons-drs#31]
Lorsqu'on se rend la première fois sur H&D (https://heros-et-dragons.fr/), le contenu est grisé, et un "sablier/spinner" apparait brièvement.

Lorsqu'on s'y rend via Google Translate (https://translate.google.com/translate?hl=&sl=fr&tl=en&u=https%3A%2F%2Fheros-et-dragons.fr%2F), pour, par exemple, partager avec des anglophones, le contenu grisé et le sablier ne disparaissent jamais.

Ceci est reproductible sur Firefox, Chrome et Edge.

La conséquence est qu'il est impossible pour un non-francophone d'explorer ce contenu, ce qui est très regrettable.

**Comment by em-squared** [comment]
C'est vrai que c'est pas idéal. Mais il s'agit plus de Google Translate qui est incapable de digérer le javascript. En effet, l'interface est gérée par du JS (beaucoup de JS). L'UI est basée sur la librairie Vuetify largement assaisonnée pour les besoins du site. On peut faire la même remarque pour la doc de Vuetify ([https://translate.google.com/translate?hl=&sl=en&tl=fr&u=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcombobox%2F&sandbox=1](https://translate.google.com/translate?hl=&sl=en&tl=fr&u=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcombobox%2F&sandbox=1)), tu verras que le JS est complètement ignoré là aussi.

Alors certes, je pourrais éventuellement retirer le spinner, mais ça serait au détriment de l'expérience utilisateur pour tous les usagers. Il sert justement à informer l'utilisateur que la page n'est pas complètement chargée.

Je ne sais pas quel est ton besoin à ce niveau, j'imagine que tu souhaites partager les classes/dons/sorts spécifiques à H&D. Si non, le SRD de D&D est 100% compatible.

J'ai peut-être fait un choix discutable sur l'interface reposant sur du JS, je le remets d'ailleurs souvent en question. Mais dans l'immédiat, ça sera un wontfix pour moi, hélas.

**Comment by paercebal** [comment]
Pas de souci.

Merci,
:-)
