### ISSUE TITLE
tableau Évolution du clerc

### ISSUE THREAD

**Issue by Palomenko** [em-squared/heros-et-dragons-drs#34]
Bonjour,

dans le tableau d'Évolution du clerc, le sort d'Aptitude de domaine divin est annoncé au niveau 6.
Dans les descriptions de chaque domaine divin, il est donné au niveau 5.
sur dd5 il semble que ce soit aussi lvl 5.

Merci pour ce site super !

**Comment by em-squared** [comment]
Salut,

Il n'y a pas d'erreur sur l'Aptitude de domaine divin. La description indique bien une aptitude aux niveau 6, 8 et 17 [(Clerc - Domaine divin)](https://heros-et-dragons.fr/classes/clerc/#domaine-divin)
En comparaison, D&D5E indique la même chose : [Cleric - Divine Domain](https://www.dndbeyond.com/classes/cleric#DivineDomain-109)

Tu dois confondre avec les sorts de domaine.

Prenons l'exemple du clerc avec le domaine divin [Gardien des traditions](https://heros-et-dragons.fr/classes/clerc/#gardien-des-traditions). Au niveau 6, il obtient l'aptitude de domaine divin [Magie ancestrale](https://heros-et-dragons.fr/classes/clerc/#magie-ancestrale). Au niveau 5 il obtient le [sort de domaine](https://heros-et-dragons.fr/classes/clerc/#sorts-de-domaine-2) _Communication avec les morts_.

À noter que le tableau d'évolution du clerc n'indique pas les niveaux auxquels sont acquis les sorts de domaine. Tous les domaines n'obtiennent pas des sorts de domaine au même niveau. Il faut donc se reporter aux domaines pour voir l'évolution des sorts de domaine.

J'espère que mon explication est claire.

Merci à toi !

**Comment by Palomenko** [comment]
Effectivement je confonds ! Merci pour la réponse rapide !

Le jeu. 8 oct. 2020 à 10:21, Maxime Moraine <notifications@github.com> a
écrit :
